- hosts: all

  pre_tasks:

    - name: Check for kubeadm
      stat:
        path: /usr/bin/kubeadm
      register: kubeadm_exists
      become: true

    - name: Reset Flannel
      command: ip link delete flannel.1
      ignore_errors: true
      tags: [ never, provision ]

    - name: Reset Kubernetes
      shell: kubeadm reset -f
      ignore_errors: true
      tags: [ never, provision ]

  roles:
    - common
    - kubeadm

  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

- hosts: master
  roles:
    - master
#    - dashboard

  post_tasks:
    - name: Get join command
      command: kubeadm token create --print-join-command
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: kubeadm_join_command_generate
      tags: [ never, provision ]

    - name: Show join command
      debug:
        msg='{{ kubeadm_join_command_generate.stdout }}'
      tags: [ never, provision ]

    - name: Get Kube config
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kube.config
      tags: [ never, provision ]

- hosts: all:!master
  gather_facts: no
  become: true
  become_method: sudo

  roles:
    - workers

  tasks:
    - name: Start k8s services
      service:
        name: "{{item}}"
        state: restarted
        enabled: yes
      with_items:
        - kubelet
        - docker
        - containerd
      tags: [ provision ]

    - name: Join cluster
      command: "{{ hostvars[groups['master'][0]].kubeadm_join_command_generate.stdout }}"
      tags: [ never, provision ]

    - name: Reload systemd files on Nodes
      systemd:
        daemon_reload: yes
