- hosts: all

  pre_tasks:
    - name: Check for kubeadm
      stat:
        path: /usr/bin/kubeadm
      register: kubeadm_exists
      become: true

    - name: Reset Kubernetes
      shell: kubeadm reset -f
      register: kubeadm_reset
      when: provisioning and kubeadm_exists.exists

  roles:
    - common
    - kubeadm

  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

- hosts: master
  roles:
    - master
#    - dashboard

  post_tasks:
    - name: Get join command
      command: kubeadm token create --print-join-command
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: kubeadm_join_command_generate
      when: provisioning

    - name: Show join command
      debug:
        msg='{{ kubeadm_join_command_generate.stdout }}'
      when: debugging and provisioning

    - name: Get Kube config
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ./kube.config
      when: provisioning

- hosts: all:!master
  roles:
    - workers

- hosts: all:!master
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups['master'][0]].kubeadm_join_command_generate.stdout }}"
      when: provisioning

    - name: Reload systemd files on Nodes
      systemd:
        daemon_reload: yes
