- hosts: all

  roles:
    - common
    - kubeadm

  post_tasks:
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
        
- hosts: master
  roles:
    - master
#    - dashboard

  post_tasks:
    - name: Get join command
      command: kubeadm token create --print-join-command
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: kubeadm_join_command_generate

    # - name: Show join command
    #   debug: 
    #     msg='{{ kubeadm_join_command_generate.stdout }}'

- hosts: all:!master
  roles:
    - workers

- hosts: all:!master
  gather_facts: no
  become: true
  become_method: sudo

  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups['master'][0]].kubeadm_join_command_generate.stdout }}"
      
    - name: Reload systemd files on Nodes
      systemd:
        daemon_reload: yes

# $ ansible bramble4 -m fetch -a 'src=/etc/kubernetes/admin.conf dest=./kube.config'
# $ KUBECONFIG=kube.config/bramble4/etc/kubernetes/admin.conf  kubectl cluster-info

# kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/alternative/kubernetes-dashboard-arm.yaml
