---
# tasks file for kubeadm

# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: Disable Swap
  shell: "{{item}}"
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
  ignore_errors: True

- include: docker.yml

- name: Pass bridged IPv4 traffic to iptables' chains
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

# https://kubernetes.io/docs/setup/independent/install-kubeadm/
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest


- name: Download GCR key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /tmp/gcr.gpg
    force: yes

- name: Install GCR key
  command: apt-key add /tmp/gcr.gpg
    
# - name: Add Google Cloud Repo Key
#   shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
#   args:
#     warn: no

- name: Add Kubernetes to Available apt Sources
  template:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list
    owner: root
    group: root
    mode: 0644


- name: Install k8s Y'all
  apt:
    name: ["kubelet={{ kubernetes_version }}-00", "kubeadm={{ kubernetes_version }}-00", "kubectl={{ kubernetes_version }}-00"]
    state: present
    update_cache: yes
    force: yes

# - name: Install k8s {{ kubernetes_package_version }} Y'all
#   apt:
#     name: "{{ item }}={{ kubernetes_package_version }}"
#     state: present
#     update_cache: yes
#     force: yes
#   with_items:
#     - kubelet
#     - kubeadm
#     - kubectl
