apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.16.11.224-172.16.11.239

    - name: certified
      protocol: layer2
      addresses:
      - 172.16.11.240/32
      auto-assign: false
