---
- name: Reset Kubernetes
  shell: kubeadm reset -f
  register: kubeadm_reset
  when: provisioning

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
