---
- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication.+$"
    line: "PasswordAuthentication no"

- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: generate locale
  locale_gen: 
    name: en_US.UTF-8
    state: present

- name: Update locale default
  lineinfile:
    dest: /etc/default/locale
    regex: "^LANG=en_GB.UTF-8$"
    line: "LANG=en_US.UTF-8"
    state: present

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"

- name: set timezone to UTC
  timezone:
    name: UTC
  register: timezone

- name: Enabling cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags:
    - boot

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no

- name: apt update
  command: apt update -y --allow-releaseinfo-change

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400

- name: Disable unneeded services
  service:
    name: "{{item}}"
    state: stopped
    enabled: no
  with_items:
    - bluetooth
    - bluealsa
    - wpa_supplicant
    - lightdm

- name: Turn off swap
  shell: "{{item}}"
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
  ignore_errors: True

- name: Disable swap on boot
  service: 
    name: dphys-swapfile
    state: stopped
    enabled: no
  register: swap_disabled


- name: Upate iptables 
  # https://github.com/kubernetes/kubernetes/issues/71305
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy 

- name: Reboot after boot params, hostname, or timezone change
  reboot:
  when: cmdline is changed or timezone is changed or hostname is changed or swap_disabled is changed
