---

- name: Reset Kubernetes Master
  shell: kubeadm reset -f
  register: kubeadm_reset

- name: Generate kubeadm token
  command: kubeadm token generate
  register: kubeadm_token_generate

- name: Set kubeadm token
  set_fact: 
    kubeadm_token: '{{ kubeadm_token_generate.stdout }}'

- name: Show k8s init command
  debug: 
    msg="kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --token={{ kubeadm_token }} --kubernetes-version=v{{ kubernetes_version }} --pod-network-cidr={{ podnet }}"

- name: "Initialize Master v{{ kubernetes_version }}"
  shell: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --token={{ kubeadm_token }} --kubernetes-version=v{{ kubernetes_version }} --pod-network-cidr={{ podnet }}
  register: kubeadm_init
  when: kubeadm_reset is succeeded

- name: Create Kubernetes config directory
  file:
    path: /root/.kube/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy admin.conf to config directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: 0755
    remote_src: yes
    backup: yes
  when: kubeadm_init
    
- name: Join Kubernetes Cluster
  shell: kubeadm join --ignore-preflight-errors=all --token {{ kubeadm_token }} {{ groups['master'][0] }}:6443 --discovery-token-unsafe-skip-ca-verification
  when: kubeadm_reset is succeeded
  register: kubeadm_join

# - name: Install Flannel
#   shell: "curl -sSL https://rawgit.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml | kubectl create -f -" 
#   warn: false

- name: Download flannel
  get_url:
    url: https://rawgit.com/coreos/flannel/{{ flannel_version }}/Documentation/kube-flannel.yml
    dest: /tmp/kube-flannel.yml
    force: yes

- name: Fix flannel yml
  replace:
    path: /tmp/kube-flannel.yml
    regexp: 'amd64'
    replace: 'arm'

- name: Install flannel
  command: kubectl apply -f /tmp/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    
- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: kubelet_poke
